require('./private/transport-seam')
require('./private/protocol')
require('./private/crypto-suite')
require('./private/counters')
require('./private/cell-codec')
require('./private/route-payload')
require('./private/fragments')
require('./private/exit-policy')
require('./private/routed-dht')
require('./private/dht-command-policy')
require('./private/dht-exit-seeds')
require('./private/dht-exit-destination-table')
require('./private/dht-exit-test-topology-grant')
require('./private/dht-exit-wire')
require('./private/dht-exit-reservation')
require('./private/dht-exit-io')
require('./private/dht-exit-immutable-get')
require('./private/dht-seed-admission')
require('./private/live-route-authority')
require('./private/routed-dht-io')
require('./private/routed-dht-traversal')
require('./private/relay-capability')
require('./private/relay-candidate-directory')
require('./private/link-setup')
require('./private/topology-grant')
require('./private/link-parameters')
require('./private/guard-link')
require('./private/relay-identity-signer')
require('./private/bootstrap-envelope')
require('./private/bootstrap-io')
require('./private/caps-responder')
require('./private/endpoint-bootstrap-authority')
require('./private/private-routing-controller')
require('./private/live-immutable-get')
require('./private/guard-reconnect-authority')
require('./private/m3-context')
require('./private/m3-adjacency-runtime')
require('./private/link-bootstrap-session')
require('./private/link-control-session')
require('./private/relay-service')
require('./private/udx-cell-endpoint')
require('./private/guard-lease')
require('./private/branch-path-authority')
require('./private/route-manager')
require('./private/branch-expiry-rotation')
require('./private/udx-loopback')

require('./private/extension-setup-channel')
require('./private/nat-punch')
require('./private/nat-traversal-live')
require('./private/extension-link-completion')
require('./private/redacted-responder-proof')
require('./private/tail-control')
require('./private/tail-extension-committer')
require('./private/route-extension-session')
require('./private/route-extension')
require('./private/final-exit-handoff')
require('./private/final-exit')
require('./private/open-route-handoff')
require('./private/final-exit-activation')
require('./private/final-exit-activation-session')

require('./private/process-codec')
require('./private/process-audit-event')
require('./private/process-config-auditor')
require('./private/process-route-cell-blackhole')
require('./private/dht-setup-audit-udx')
// The coordinator spawns role processes with `child_process`, so this stays
// Node-only. The capture-oracle tests read pcap bytes from disk and are
// Node-only for the same reason.
if (!global.Bare) {
  require('./private/process-control')
  require('./private/route-oracles')
}

// The eleven-role live scenarios bind the 127.64.x.1 tuples, which macOS and
// Windows refuse without per-address configuration (KI-2). They are not part of
// this portable aggregate; run them with `npm run test:private:process:node`
// and `npm run test:private:process:bare`, as the Linux CI job does. The
// privileged namespace gates are separated the same way.
